### ISSUE TITLE
初始化项目报错，没有权限

### ISSUE THREAD

**Issue by qq-lilong** [Kayshen-X/rn4oh#1]
shanhs@shanhsdeMac-mini 666 % npx rn4oh init awesome-app -v 1.0.0 
✖ 检查版本是否存在...
初始化项目时发生错误: GitError: git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

    at Object.action (/Users/shanhs/.npm/_npx/cc022ef4fcbc0ff8/node_modules/simple-git/dist/cjs/index.js:1451:25)
    at PluginStore.exec (/Users/shanhs/.npm/_npx/cc022ef4fcbc0ff8/node_modules/simple-git/dist/cjs/index.js:1500:29)
    at /Users/shanhs/.npm/_npx/cc022ef4fcbc0ff8/node_modules/simple-git/dist/cjs/index.js:1927:43
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (/Users/shanhs/.npm/_npx/cc022ef4fcbc0ff8/node_modules/simple-git/dist/cjs/index.js:1925:16)
    at GitExecutorChain.<anonymous> (/Users/shanhs/.npm/_npx/cc022ef4fcbc0ff8/node_modules/simple-git/dist/cjs/index.js:1909:44)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/shanhs/.npm/_npx/cc022ef4fcbc0ff8/node_modules/simple-git/dist/cjs/index.js:52:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  task: {
    commands: [
      'ls-remote',
      '--tags',
      'git@github.com:Kayshen-X/rn4oh-template.git'
    ],
    format: 'utf-8',
    parser: [Function: parser]
  }
}

**Comment by Kayshen-X** [comment]
#2 already fix
